server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://10.225.12.96:8763/eureka/

spring:
  application:
    name: orchid-gateway
  cloud:
    gateway:
      ##自动搜索微服务列表创建路由
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      ## 手动定义路由
#      routes:
#        - id: docker-example
#          uri: lb://docker-example
#          predicates:
#          - Path=/docker-example/**
#          filters:
#            - StripPrefix=1
