server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://10.225.12.98:3306/test?Unicode=true&characterEncoding=UTF-8
    username: root
    password: root


#thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/ #模板文件位置
    suffix: .html #模板文件后缀
    cache: false #是否启用缓存
    encoding: utf-8 #编码
    mode: HTML #严格的HTML语法校验
    servlet:
      content-type: text/html

mybatis-plus:
  configuration:
    auto-mapping-behavior: FULL
    auto-mapping-unknown-column-behavior: WARNING
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      table-prefix:
  log: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.orchid.auth.entity
