server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://10.225.12.98:3306/test?Unicode=true&characterEncoding=UTF-8
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.orchid.oauth2.server.entity
  log: true
