spring:
  application:
    name: orchid-eureka
  profiles:
    active: default
---
spring:
  profiles: default
server:
  port: 8761
eureka:
  hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
